apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: projeto-infra
  title: Solicitação de Projeto de Infraestrutura
  description: Template para solicitar projeto com recursos
spec:
  type: infrastructure
  owner: equipe-devops
  parameters:
    - title: Informações do Projeto
      required:
        - nomeProjeto
      properties:
        nomeProjeto:
          title: Nome do Projeto
          type: string
          description: Nome identificador do projeto

    - title: Recursos do Projeto
      required:
        - memoria
        - cpu
      properties:
        memoria:
          title: Quantidade de Memória
          type: string
          enum:
            - "2Gi"
            - "4Gi"
            - "8Gi"
          enumNames:
            - "2 GB"
            - "4 GB"
            - "8 GB"
          description: Escolha a quantidade de memória
        cpu:
          title: Quantidade de CPU
          type: string
          enum:
            - "1"
            - "2"
            - "4"
          enumNames:
            - "1 vCPU"
            - "2 vCPU"
            - "4 vCPU"
          description: Escolha a quantidade de CPU

    - title: Confirmação e Custo
      description: Confirme a criação do projeto com base no custo estimado.
      required:
        - confirmarCriacao
      properties:
        custoEstimado:
          title: Custo Estimado
          type: string
          ui:field: CustoEstimado
          readOnly: true
          description: Valor calculado dinamicamente com base na memória e CPU.
        confirmarCriacao:
          title: Confirmar criação do projeto?
          type: boolean
          description: Marque para prosseguir com a solicitação.

  steps:
    - id: calcular-custo
      name: Calcular Custo Estimado
      action: debug:log
      input:
        message: |
          🔍 Cálculo de custo estimado:
          - CPU: ${{ parameters.cpu }} x R$1 = R$${{ parameters.cpu }}
          - Memória: ${{ parameters.memoria }} x R$3

          💰 Total estimado: R$${{ parameters.cpu | parseInt | multiply(1) + (parameters.memoria | replace("Gi", "") | parseInt | multiply(3)) }}

    - id: verificar-confirmacao
      name: Verificar Confirmação
      action: debug:log
      input:
        message: |
          ${{
            parameters.confirmarCriacao
              ? "✅ Usuário confirmou criação. Prosseguindo..."
              : "🚫 Usuário NÃO confirmou. Template será encerrado."
          }}

    - id: criar-ticket
      name: Criar Ticket no Jira
      if: ${{ parameters.confirmarCriacao }}
      action: custom:jira:createTicket
      input:
        projectKey: ZT
        issueType: Task
        summary: "[Infra] Solicitação de Projeto: ${{ parameters.nomeProjeto }}"
        description: |
          Solicitação de projeto criada via Backstage:
          - Projeto: ${{ parameters.nomeProjeto }}
          - Memória: ${{ parameters.memoria }}
          - CPU: ${{ parameters.cpu }}
          - 💰 Custo estimado: R$${{ parameters.cpu | parseInt | multiply(1) + (parameters.memoria | replace("Gi", "") | parseInt | multiply(3)) }}

  output:
    text:
      - title: Resultado
        content: |
          ✅ Solicitação criada com sucesso!

          📦 Detalhes:
          - Projeto: ${{ parameters.nomeProjeto }}
          - Memória: ${{ parameters.memoria }}
          - CPU: ${{ parameters.cpu }}
          - 💰 Custo estimado: R$${{ parameters.cpu | parseInt | multiply(1) + (parameters.memoria | replace("Gi", "") | parseInt | multiply(3)) }}

          Obrigado por utilizar o Backstage!
