apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: projeto-infra
  title: Solicitação de Projeto de Infraestrutura
  description: Template para solicitar projeto com recursos
spec:
  type: infrastructure
  owner: equipe-devops
  parameters:
    - title: Informações do Projeto
      required:
        - nomeProjeto
        - usuario
        - email
        - area
        - site
      properties:
        nomeProjeto:
          title: Nome do Projeto
          type: string
        usuario:
          title: Nome do Usuário
          type: string
        email:
          title: E-mail
          type: string
          format: email
        area:
          title: Área
          type: string
          enum:
            - Infraestrutura
            - Desenvolvimento
            - Operações
            - Dados
            - Segurança
        site:
          title: Site
          type: string
          enum:
            - DFCTO
            - RSIND
            - PRCTA
            - SPJGR
            - SP-SANTA EFIGENIA
            - SPCTP
            - SPPAS
            - SCFNS
            - MGBHF
            - RJBAR
            - AMAFP
            - PACCP
            - BATCS
            - Outro
        siteOutroEndereco:
          title: Endereço (se site for "Outro")
          type: string
          ui:widget: textarea
        siteOutroJustificativa:
          title: Justificativa (se site for "Outro")
          type: string
          ui:widget: textarea

    - title: Recursos Necessários
      required: [cpu, memoria, disco]
      properties:
        cpu:
          title: CPU (cores)
          type: number
          minimum: 1
        memoria:
          title: Memória (GB)
          type: number
          minimum: 1
        disco:
          title: Disco (GB)
          type: number
          minimum: 1
        readWriteMany:
          title: Precisa de múltipla escrita (ReadWriteMany)?
          type: boolean
          default: false

    - title: Orçamento
      required:
        - idOrcamento
        - megaProjeto
        - acaoInversora
      properties:
        idOrcamento:
          title: ID Orçamentário
          type: string
        megaProjeto:
          title: Mega Projeto (Diretoria)
          type: string
        acaoInversora:
          title: Ação Inversora
          type: string

    - title: Confirmação
      required:
        - confirmarCriacao
      properties:
        custoSimulado:
          title: 💰 Custo Estimado
          type: string
          default: "R$25"
          readOnly: true
        confirmarCriacao:
          title: Confirmar criação do projeto?
          type: boolean

  steps:
    - id: verificar-confirmacao
      name: Verificar Confirmação
      action: debug:log
      input:
        message: |
          ${{
            parameters.confirmarCriacao
              ? "✅ Usuário confirmou criação. Prosseguindo..."
              : "🚫 Usuário NÃO confirmou. Template será encerrado."
          }}

    - id: criar-ticket
      name: Criar Ticket no Jira
      if: ${{ parameters.confirmarCriacao }}
      action: custom:jira:createTicket
      input:
        projectKey: ZT
        issueType: Task
        summary: "[Infra] Solicitação: ${{ parameters.nomeProjeto }}"
        description: |
          📝 Solicitação de Infraestrutura criada via Backstage:

          📌 Projeto: ${{ parameters.nomeProjeto }}
          👤 Solicitante: ${{ parameters.usuario }} - ${{ parameters.email }}
          🏢 Área: ${{ parameters.area }}

          📍 Site: ${{ parameters.site }}
          ${{
            parameters.site == "Outro"
              ? "📫 Endereço: " + parameters.siteOutroEndereco + "\n📄 Justificativa: " + parameters.siteOutroJustificativa
              : ""
          }}

          ⚙️ Recursos:
          - CPU: ${{ parameters.cpu }}
          - Memória: ${{ parameters.memoria }}
          - Disco: ${{ parameters.disco }} GB
          - RWX: ${{ parameters.readWriteMany }}

          💰 Orçamento:
          - ID: ${{ parameters.idOrcamento }}
          - Mega Projeto: ${{ parameters.megaProjeto }}
          - Ação Inversora: ${{ parameters.acaoInversora }}

          ✅ Solicitação confirmada pelo usuário.

  output:
    text:
      - title: Solicitação enviada com sucesso!
        content: |
          A abertura de demanda foi realizada e o ticket foi criado no Jira com os dados fornecidos.
