apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: projeto-infra
  title: Solicitação de Projeto de Infraestrutura
  description: Template para solicitar projeto com recursos
spec:
  type: infrastructure
  owner: equipe-devops
  path: ./template.yaml
